const actionTypes = Object.freeze({
    //APP
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_COMFIRM_MODAL: 'SET_CONTENT_OF_COMFIRM_MODAL',

    //USER
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT'
})

export default actionTypes;